base_url = "https://sapi.dev"
title = "Sapi's online fief"

compile_sass = true

highlight_code = true

build_search_index = false

check_external_links = true

taxonomies = [
    { name = "tags", rss = true },
    { name = "authors", rss = true }
]

[extra]
show_word_count = true
show_reading_time = true

date_format = "%b %e, %Y"

home = "home"

sam_menu = [
    { text = "posts", link = "/posts" },
    { text = "tools", link = "/tools" },
    { text = "about", link = "/about" }
]

sam_bottom_menu = true

[extra.sam_footer]
text = "bio.link/sapi"
